velocity_smoother:
  ros__parameters:
    use_sim_time: false
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "OPEN_LOOP"
    max_velocity: [0.15, 0.0, 0.3]
    min_velocity: [-0.15, 0.0, -0.3]
    max_accel: [0.02, 0.0, 0.02]
    max_decel: [-1.0, 0.0, -1.0]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 100000000.0
    enable_stamped_cmd_vel: false